In [5]:
from keras.datasets import mnist

Using TensorFlow backend.
/Users/test/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/test/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/test/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/test/opt/anaconda3/lib/python3.7/site-pa

In [6]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
len(test_images)

10000

In [11]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
from keras import models
from keras import layers

In [13]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax')) 

In [14]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [15]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [16]:
from keras.utils import to_categorical


In [17]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [18]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
60000/60000 [==============================] - 6s 96us/step - loss: 0.2565 - accuracy: 0.9256
Epoch 2/5
60000/60000 [==============================] - 6s 98us/step - loss: 0.1043 - accuracy: 0.9694
Epoch 3/5
60000/60000 [==============================] - 4s 74us/step - loss: 0.0688 - accuracy: 0.9789
Epoch 4/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.0497 - accuracy: 0.9852
Epoch 5/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0380 - accuracy: 0.9885


In [19]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 0s 42us/step


In [20]:
print('test_acc:', test_acc)

test_acc: 0.9800000190734863


In [21]:
import numpy as np


In [22]:
x = np.array(12)
 

In [23]:
x

array(12)

In [24]:
x.ndim

0

In [25]:
x = np.array([12, 3, 6, 14])

In [26]:
x

array([12,  3,  6, 14])

In [27]:
x.ndim

1

In [28]:
x = np.array([[5, 78, 2, 34, 0],
                  [6, 79, 3, 35, 1],
                  [7, 80, 4, 36, 2]])

In [29]:
x.ndim

2

In [30]:
x = np.array([[[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]],
                  [[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]],
                  [[5, 78, 2, 34, 0],
                   [6, 79, 3, 35, 1],
                   [7, 80, 4, 36, 2]]])

In [31]:
x.ndim

3

In [32]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [33]:
print(train_images.ndim)

3


In [34]:
print(train_images.shape)

(60000, 28, 28)


In [35]:
print(train_images.dtype)

uint8


In [36]:
digit = train_images[4]

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

In [ ]:
my_slice = train_images[10:100]

In [ ]:
print(my_slice.shape)

In [ ]:
my_slice = train_images[10:100, :, :]           

In [ ]:
my_slice.shape

In [ ]:
my_slice = train_images[10:100, 0:28, 0:28]

In [ ]:
my_slice.shape

In [ ]:
my_slice = train_images[:, 14:, 14:]

In [ ]:
batch = train_images[:128]

In [ ]:
batch = train_images[128:256]